apiVersion: v1
kind: ConfigMap
metadata:
  name: pitflow-registry-config
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-registry
    app.kubernetes.io/instance: pitflow-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
data:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"
