apiVersion: v1
kind: ConfigMap
metadata:
  name: pitflow-registry-config
  labels:
    app: pitflow-registry
data:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"
