apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pitflow-registry
  annotations:
    alb.ingress.kubernetes.io/group.name: pitflow
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /registry
            pathType: Prefix
            backend:
              service:
                name: pitflow-registry
                port:
                  name: http
