apiVersion: v1
kind: Secret
metadata:
  name: pitflow-registry-secrets
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-registry
    app.kubernetes.io/instance: pitflow-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  DATADOG_API_KEY: "${DATADOG_API_KEY}"
