apiVersion: v1
kind: Secret
metadata:
  name: pitflow-registry-secrets
  labels:
    app: pitflow-registry
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  DATADOG_API_KEY: "${DATADOG_API_KEY}"
